[package]
name = "rgctl-lang-csharp"
version = "0.4.10"
edition.workspace = true
rust-version.workspace = true
description = "rgctl language plugin: csharp"
license = "MIT OR Apache-2.0"

[dependencies]
rgctl-plugin-api = { workspace = true }
rgctl-registry = { workspace = true }
rgctl-plugin-helpers = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-c-sharp = "0.23.5"
serde_json = "1"
