//! Compiled vocabulary matrix + bag-of-tokens accumulator.
//!
//! `vocab-accumulate-v1` is FNV rows from `build.rs`. `vocab-accumulate-v2` is a
//! matrix distilled from rgctl's own token list through a teacher embedder
//! (`rgctl semantic distill`, typically code-daemon).

use crate::semantic_embedder::SemanticEmbedder;
use rgctl_error::{Error, Result};
use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

/// Stable model id for the compiled vocab matrix (`v1` FNV, `v2` distilled).
pub const VOCAB_ACCUMULATE_MODEL_ID: &str = match option_env!("RGCTL_VOCAB_MODEL_ID") {
    Some(id) => id,
    None => "vocab-accumulate-v1",
};

/// Model id written into distilled `assets/vocab_matrix.bin` files.
pub const VOCAB_ACCUMULATE_DISTILLED_ID: &str = "vocab-accumulate-v2";

/// Native vocabulary embedding width produced by `build.rs`.
pub const VOCAB_NATIVE_DIMENSIONS: usize = 256;

/// Identifier list compiled into the binary (`assets/vocab_tokens.txt`).
pub const DEFAULT_VOCAB_TOKEN_LIST: &str = include_str!("../assets/vocab_tokens.txt");

const MAGIC: &[u8; 4] = b"RBVK";
const VERSION: u32 = 1;

static EMBEDDED: OnceLock<&'static [u8]> = OnceLock::new();
static ACCUMULATOR: OnceLock<std::result::Result<TokenSpaceAccumulator, String>> = OnceLock::new();

fn embedded_bytes() -> &'static [u8] {
    EMBEDDED.get_or_init(|| {
        // Generated by build.rs into OUT_DIR; path injected via rustc-env.
        include_bytes!(env!("RGCTL_VOCAB_MATRIX"))
    })
}

/// Bag-of-tokens accumulator over the compiled int8 vocabulary matrix.
#[derive(Debug, Clone)]
pub struct TokenSpaceAccumulator {
    token_to_idx: HashMap<String, u32>,
    weights: Vec<i8>,
    dimensions: usize,
}

impl TokenSpaceAccumulator {
    /// Parse and validate a vocab matrix blob.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        if bytes.len() < 16 {
            return Err(Error::ConfigError(
                "vocab matrix truncated: header too short".into(),
            ));
        }
        if &bytes[0..4] != MAGIC {
            return Err(Error::ConfigError(
                "vocab matrix: bad magic (expected RBVK)".into(),
            ));
        }
        let version = u32::from_le_bytes(bytes[4..8].try_into().unwrap());
        if version != VERSION {
            return Err(Error::ConfigError(format!(
                "vocab matrix: unsupported version {version}"
            )));
        }
        let n_tokens = u32::from_le_bytes(bytes[8..12].try_into().unwrap()) as usize;
        let dimensions = u32::from_le_bytes(bytes[12..16].try_into().unwrap()) as usize;
        if dimensions == 0 || dimensions % 8 != 0 {
            return Err(Error::ConfigError(format!(
                "vocab matrix: invalid dimensions {dimensions}"
            )));
        }
        if n_tokens == 0 {
            return Err(Error::ConfigError("vocab matrix: empty token table".into()));
        }

        let mut offset = 16usize;
        let mut token_to_idx = HashMap::with_capacity(n_tokens);
        for idx in 0..n_tokens {
            if offset + 2 > bytes.len() {
                return Err(Error::ConfigError(
                    "vocab matrix truncated while reading tokens".into(),
                ));
            }
            let len = u16::from_le_bytes(bytes[offset..offset + 2].try_into().unwrap()) as usize;
            offset += 2;
            if len == 0 || offset + len > bytes.len() {
                return Err(Error::ConfigError(format!(
                    "vocab matrix: invalid token length at index {idx}"
                )));
            }
            let token = std::str::from_utf8(&bytes[offset..offset + len])
                .map_err(|err| Error::ConfigError(format!("vocab matrix utf8: {err}")))?
                .to_ascii_lowercase();
            offset += len;
            token_to_idx.insert(token, idx as u32);
        }

        let weights_len = n_tokens
            .checked_mul(dimensions)
            .ok_or_else(|| Error::ConfigError("vocab matrix: weights overflow".into()))?;
        if offset + weights_len != bytes.len() {
            return Err(Error::ConfigError(format!(
                "vocab matrix: trailing size mismatch (offset={offset}, weights={weights_len}, len={})",
                bytes.len()
            )));
        }

        let mut weights = Vec::with_capacity(weights_len);
        for &b in &bytes[offset..] {
            weights.push(b as i8);
        }

        Ok(Self {
            token_to_idx,
            weights,
            dimensions,
        })
    }

    /// Shared process-wide accumulator over the compiled matrix.
    pub fn global() -> Result<&'static TokenSpaceAccumulator> {
        let slot = ACCUMULATOR
            .get_or_init(|| Self::from_bytes(embedded_bytes()).map_err(|err| err.to_string()));
        match slot {
            Ok(acc) => Ok(acc),
            Err(msg) => Err(Error::ConfigError(msg.clone())),
        }
    }

    /// Vocabulary embedding width.
    pub fn dimensions(&self) -> usize {
        self.dimensions
    }

    /// Number of tokens in the table.
    pub fn token_count(&self) -> usize {
        self.token_to_idx.len()
    }

    /// Accumulate tokens into an L2-normalized dense vector of native width.
    ///
    /// Tokens missing from the table contribute a deterministic FNV row (OOV fallback).
    pub fn accumulate_tokens(&self, tokens: &HashSet<String>) -> Vec<f32> {
        let mut dense = vec![0.0f32; self.dimensions];
        let mut matched = 0usize;
        for token in tokens {
            let key = token.to_ascii_lowercase();
            if let Some(&idx) = self.token_to_idx.get(&key) {
                matched += 1;
                let start = idx as usize * self.dimensions;
                let row = &self.weights[start..start + self.dimensions];
                for (d, &w) in row.iter().enumerate() {
                    dense[d] += f32::from(w);
                }
            } else if (3..=48).contains(&key.len()) {
                matched += 1;
                add_fnv_row(&mut dense, key.as_bytes());
            }
        }
        if matched > 0 {
            l2_normalize(&mut dense);
        }
        dense
    }

    /// Tokenize text (identifier-like) and accumulate, optionally resized to `out_dims`.
    pub fn accumulate_text(&self, text: &str, out_dims: usize) -> Vec<f32> {
        let mut tokens = HashSet::new();
        rgctl_graph::tokenize_string_into(text, &mut tokens);
        // Also accept simple alphanumeric splits for query strings.
        for piece in text.split(|c: char| !c.is_alphanumeric() && c != '_') {
            if piece.len() >= rgctl_graph::MIN_TOKEN_LEN {
                tokens.insert(piece.to_ascii_lowercase());
            }
        }
        let native = self.accumulate_tokens(&tokens);
        resize_dense(&native, out_dims)
    }
}

/// Parse `assets/vocab_tokens.txt` (one token per line, `#` comments).
pub fn parse_vocab_token_list(text: &str) -> Vec<String> {
    let mut tokens: Vec<String> = text
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(str::to_ascii_lowercase)
        .filter(|token| (3..=48).contains(&token.len()))
        .collect();
    tokens.sort_unstable();
    tokens.dedup();
    tokens
}

/// Encode a row-major int8 matrix as an RBVK blob.
pub fn encode_rbvk(tokens: &[String], weights: &[i8], dimensions: usize) -> Result<Vec<u8>> {
    if dimensions == 0 || !dimensions.is_multiple_of(8) {
        return Err(Error::ConfigError(
            "vocab matrix dimensions must be a positive multiple of 8".into(),
        ));
    }
    let expected = tokens
        .len()
        .checked_mul(dimensions)
        .ok_or_else(|| Error::ConfigError("vocab matrix: weights overflow".into()))?;
    if weights.len() != expected {
        return Err(Error::ConfigError(format!(
            "vocab matrix: expected {} weights, got {}",
            expected,
            weights.len()
        )));
    }
    let mut out = Vec::new();
    out.extend_from_slice(MAGIC);
    out.extend_from_slice(&VERSION.to_le_bytes());
    out.extend_from_slice(&(tokens.len() as u32).to_le_bytes());
    out.extend_from_slice(&(dimensions as u32).to_le_bytes());
    for token in tokens {
        let bytes = token.as_bytes();
        let len = u16::try_from(bytes.len())
            .map_err(|_| Error::ConfigError("vocab token longer than u16".into()))?;
        if len == 0 {
            return Err(Error::ConfigError("empty vocab token".into()));
        }
        out.extend_from_slice(&len.to_le_bytes());
        out.extend_from_slice(bytes);
    }
    out.extend(weights.iter().map(|w| *w as u8));
    Ok(out)
}

/// Distill `tokens` through `embedder` into an RBVK blob of `out_dims`.
///
/// Teacher is typically code-daemon. Batches keep ONNX sessions fed without
/// holding a dense `tokens × dims` buffer for the whole vocabulary.
pub fn distill_vocab_matrix(
    embedder: &dyn SemanticEmbedder,
    tokens: &[String],
    out_dims: usize,
    batch_size: usize,
) -> Result<Vec<u8>> {
    if tokens.is_empty() {
        return Err(Error::ConfigError(
            "cannot distill an empty token list".into(),
        ));
    }
    let chunk = batch_size.max(1);
    let mut weights = Vec::with_capacity(tokens.len() * out_dims);
    for batch in tokens.chunks(chunk) {
        let refs: Vec<&str> = batch.iter().map(String::as_str).collect();
        let dense = embedder.embed_batch(&refs)?;
        if dense.len() != batch.len() {
            return Err(Error::ConfigError(format!(
                "embed_batch returned {} rows for {} tokens",
                dense.len(),
                batch.len()
            )));
        }
        for row in dense {
            let resized = resize_dense(&row, out_dims);
            weights.extend(quantize_unit_i8(&resized));
        }
    }
    encode_rbvk(tokens, &weights, out_dims)
}

fn quantize_unit_i8(row: &[f32]) -> Vec<i8> {
    row.iter()
        .map(|value| {
            let scaled = (*value * 127.0).round();
            scaled.clamp(-127.0, 127.0) as i8
        })
        .collect()
}

fn fnv1a(bytes: &[u8]) -> u64 {
    let mut hash: u64 = 0xcbf29ce484222325;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

fn add_fnv_row(dense: &mut [f32], token: &[u8]) {
    let base = fnv1a(token);
    for (d, slot) in dense.iter_mut().enumerate() {
        let mixed = base
            .wrapping_add((d as u64).wrapping_mul(0x9E3779B97F4A7C15))
            .wrapping_mul(0x100000001b3);
        let centered = (mixed % 251) as i32 - 125;
        *slot += centered as f32;
    }
}

fn l2_normalize(vec: &mut [f32]) {
    let sum_sq: f32 = vec.iter().map(|x| x * x).sum();
    if sum_sq > 0.0 {
        let norm = sum_sq.sqrt();
        for v in vec.iter_mut() {
            *v /= norm;
        }
    }
}

fn resize_dense(native: &[f32], out_dims: usize) -> Vec<f32> {
    if out_dims == native.len() {
        return native.to_vec();
    }
    let mut out = vec![0.0f32; out_dims];
    let copy = native.len().min(out_dims);
    out[..copy].copy_from_slice(&native[..copy]);
    if copy > 0 {
        l2_normalize(&mut out);
    }
    out
}

/// Embedder backed by [`TokenSpaceAccumulator`].
#[derive(Debug, Clone)]
pub struct VocabAccumulateEmbedder {
    dimensions: usize,
}

impl VocabAccumulateEmbedder {
    /// Create an embedder that outputs `dimensions` floats (prefer 256).
    pub fn new(dimensions: usize) -> Result<Self> {
        if dimensions == 0 || dimensions % 8 != 0 {
            return Err(Error::ConfigError(
                "vocab embedder dimensions must be a positive multiple of 8".into(),
            ));
        }
        // Ensure matrix loads at construction time.
        let _ = TokenSpaceAccumulator::global()?;
        Ok(Self { dimensions })
    }
}

impl crate::semantic_embedder::SemanticEmbedder for VocabAccumulateEmbedder {
    fn model_id(&self) -> &str {
        VOCAB_ACCUMULATE_MODEL_ID
    }

    fn dimensions(&self) -> usize {
        self.dimensions
    }

    fn embed(&self, text: &str) -> Result<Vec<f32>> {
        let acc = TokenSpaceAccumulator::global()?;
        Ok(acc.accumulate_text(text, self.dimensions))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::semantic_embedder::SemanticEmbedder;

    #[test]
    fn embedded_matrix_loads() {
        let acc = TokenSpaceAccumulator::global().expect("load vocab");
        assert!(acc.token_count() > 100);
        assert_eq!(acc.dimensions(), VOCAB_NATIVE_DIMENSIONS);
    }

    #[test]
    fn known_tokens_stable_bits() {
        let emb = VocabAccumulateEmbedder::new(256).unwrap();
        let a = emb.embed_binary("checkout order cart process").unwrap();
        let b = emb.embed_binary("checkout order cart process").unwrap();
        assert_eq!(a, b);
        assert_eq!(a.len(), 32);
    }

    #[test]
    fn unknown_tokens_use_fnv_oov_fallback() {
        let acc = TokenSpaceAccumulator::global().unwrap();
        let mut tokens = HashSet::new();
        tokens.insert("zzzxqnotinvocab999".into());
        let a = acc.accumulate_tokens(&tokens);
        let b = acc.accumulate_tokens(&tokens);
        assert_eq!(a, b);
        assert!(a.iter().any(|&x| x != 0.0));
    }

    #[test]
    fn distill_round_trip_with_hash_teacher() {
        let tokens = parse_vocab_token_list("checkout\ncart\norder\n");
        let teacher = crate::semantic_embedder::SignHashEmbedder::new(64);
        let blob = distill_vocab_matrix(&teacher, &tokens, 64, 2).unwrap();
        let acc = TokenSpaceAccumulator::from_bytes(&blob).unwrap();
        assert_eq!(acc.token_count(), 3);
        assert_eq!(acc.dimensions(), 64);
        let query = acc.accumulate_text("checkout cart", 64);
        assert_eq!(query.len(), 64);
        assert!(query.iter().any(|&x| x != 0.0));
    }

    #[test]
    fn corrupt_matrix_rejected() {
        let err = TokenSpaceAccumulator::from_bytes(b"XXXX").unwrap_err();
        assert!(err.to_string().contains("magic") || err.to_string().contains("truncated"));
    }

    #[test]
    fn dim_packing_resize() {
        let emb = VocabAccumulateEmbedder::new(64).unwrap();
        let floats = emb.embed("checkout order").unwrap();
        assert_eq!(floats.len(), 64);
        assert_eq!(emb.embed_binary("checkout order").unwrap().len(), 8);
    }
}
