[package]
name = "rgctl-lang-python"
version = "0.4.11"
edition.workspace = true
rust-version.workspace = true
description = "rgctl language plugin: python"
license = "MIT OR Apache-2.0"

[dependencies]
rgctl-plugin-api = { workspace = true }
rgctl-registry = { workspace = true }
rgctl-plugin-helpers = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-python = "0.25"
rgctl-semantic = { workspace = true }
serde_json = "1"
